### ISSUE TITLE
7.3.1 Repository Image not working

### ISSUE THREAD

**Issue by MariusGrunenberg** [aborroy/alfresco-dockerx-builder#6]
When building the Repo Enterprise image for 7.3.1, I get following error, when trying to start:

```
2023-02-16 13:27:04 16-Feb-2023 12:27:04.699 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/api-explorer.war]
2023-02-16 13:27:04 16-Feb-2023 12:27:04.729 SEVERE [main] org.apache.catalina.startup.ContextConfig.beforeStart Exception fixing docBase for context [/api-explorer]
2023-02-16 13:27:04     java.util.zip.ZipException: zip END header not found
2023-02-16 13:27:04             at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
2023-02-16 13:27:04             at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
2023-02-16 13:27:04             at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
2023-02-16 13:27:04             at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
2023-02-16 13:27:04             at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
2023-02-16 13:27:04             at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
2023-02-16 13:27:04             at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
2023-02-16 13:27:04             at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
2023-02-16 13:27:04             at java.base/sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:103)
2023-02-16 13:27:04             at java.base/sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:72)
2023-02-16 13:27:04             at java.base/sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:168)
2023-02-16 13:27:04             at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:131)
2023-02-16 13:27:04             at java.base/sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:92)
2023-02-16 13:27:04             at org.apache.catalina.startup.ExpandWar.expand(ExpandWar.java:128)
2023-02-16 13:27:04             at org.apache.catalina.startup.ContextConfig.fixDocBase(ContextConfig.java:820)
2023-02-16 13:27:04             at org.apache.catalina.startup.ContextConfig.beforeStart(ContextConfig.java:959)
2023-02-16 13:27:04             at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:305)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:182)
2023-02-16 13:27:04             at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726)
2023-02-16 13:27:04             at org.apache.catalina.core.ContainerBase.access$000(ContainerBase.java:129)
2023-02-16 13:27:04             at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:149)
2023-02-16 13:27:04             at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:139)
2023-02-16 13:27:04             at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
2023-02-16 13:27:04             at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:696)
2023-02-16 13:27:04             at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:696)
2023-02-16 13:27:04             at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1024)
2023-02-16 13:27:04             at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1911)
2023-02-16 13:27:04             at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2023-02-16 13:27:04             at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-02-16 13:27:04             at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
2023-02-16 13:27:04             at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
2023-02-16 13:27:04             at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:825)
2023-02-16 13:27:04             at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:475)
2023-02-16 13:27:04             at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1618)
2023-02-16 13:27:04             at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:319)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
2023-02-16 13:27:04             at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:946)
2023-02-16 13:27:04             at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2023-02-16 13:27:04             at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
2023-02-16 13:27:04             at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
2023-02-16 13:27:04             at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-02-16 13:27:04             at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
2023-02-16 13:27:04             at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
2023-02-16 13:27:04             at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
2023-02-16 13:27:04             at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2023-02-16 13:27:04             at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2023-02-16 13:27:04             at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2023-02-16 13:27:04             at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
2023-02-16 13:27:04             at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-02-16 13:27:04             at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-02-16 13:27:04             at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-02-16 13:27:04             at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-02-16 13:27:04             at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
2023-02-16 13:27:04             at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
2023-02-16 13:27:04 16-Feb-2023 12:27:04.747 SEVERE [main] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive [/usr/local/tomcat/webapps/api-explorer.war]
2023-02-16 13:27:04     java.lang.IllegalStateException: Error starting child
2023-02-16 13:27:04             at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:729)
2023-02-16 13:27:04             at org.apache.catalina.core.ContainerBase.access$000(ContainerBase.java:129)
2023-02-16 13:27:04             at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:149)
2023-02-16 13:27:04             at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:139)
2023-02-16 13:27:04             at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
2023-02-16 13:27:04             at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:696)
2023-02-16 13:27:04             at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:696)
2023-02-16 13:27:04             at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1024)
2023-02-16 13:27:04             at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1911)
2023-02-16 13:27:04             at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2023-02-16 13:27:04             at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-02-16 13:27:04             at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
2023-02-16 13:27:04             at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
2023-02-16 13:27:04             at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:825)
2023-02-16 13:27:04             at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:475)
2023-02-16 13:27:04             at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1618)
2023-02-16 13:27:04             at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:319)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
2023-02-16 13:27:04             at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:946)
2023-02-16 13:27:04             at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2023-02-16 13:27:04             at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
2023-02-16 13:27:04             at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
2023-02-16 13:27:04             at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-02-16 13:27:04             at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
2023-02-16 13:27:04             at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
2023-02-16 13:27:04             at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
2023-02-16 13:27:04             at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2023-02-16 13:27:04             at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2023-02-16 13:27:04             at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2023-02-16 13:27:04             at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
2023-02-16 13:27:04             at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-02-16 13:27:04             at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-02-16 13:27:04             at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-02-16 13:27:04             at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-02-16 13:27:04             at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
2023-02-16 13:27:04             at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
2023-02-16 13:27:04     Caused by: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.WarResourceSet@266374ef]
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:139)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:173)
2023-02-16 13:27:04             at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:727)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2023-02-16 13:27:04             at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4885)
2023-02-16 13:27:04             at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5023)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2023-02-16 13:27:04             at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726)
2023-02-16 13:27:04             ... 41 more
2023-02-16 13:27:04     Caused by: java.lang.IllegalArgumentException: java.io.IOException: java.lang.reflect.InvocationTargetException
2023-02-16 13:27:04             at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.initInternal(AbstractSingleArchiveResourceSet.java:143)
2023-02-16 13:27:04             at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
2023-02-16 13:27:04             ... 48 more
2023-02-16 13:27:04     Caused by: java.io.IOException: java.lang.reflect.InvocationTargetException
2023-02-16 13:27:04             at org.apache.tomcat.util.compat.Jre9Compat.jarFileNewInstance(Jre9Compat.java:209)
2023-02-16 13:27:04             at org.apache.tomcat.util.compat.JreCompat.jarFileNewInstance(JreCompat.java:226)
2023-02-16 13:27:04             at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.initInternal(AbstractSingleArchiveResourceSet.java:140)
2023-02-16 13:27:04             ... 49 more
2023-02-16 13:27:04     Caused by: java.lang.reflect.InvocationTargetException
2023-02-16 13:27:04             at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2023-02-16 13:27:04             at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
2023-02-16 13:27:04             at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2023-02-16 13:27:04             at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
2023-02-16 13:27:04             at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
2023-02-16 13:27:04             at org.apache.tomcat.util.compat.Jre9Compat.jarFileNewInstance(Jre9Compat.java:206)
2023-02-16 13:27:04             ... 51 more
2023-02-16 13:27:04     Caused by: java.util.zip.ZipException: zip END header not found
2023-02-16 13:27:04             at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
2023-02-16 13:27:04             at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
2023-02-16 13:27:04             at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
2023-02-16 13:27:04             at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
2023-02-16 13:27:04             at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
2023-02-16 13:27:04             at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
2023-02-16 13:27:04             at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
2023-02-16 13:27:04             at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
```

And also: 

```
2023-02-16 13:27:16 2023-02-16 12:27:16,077  ERROR [web.context.ContextLoader] [main] Context initialization failed
2023-02-16 13:27:16 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.beans.factory.config.CustomEditorConfigurer#0' defined in class path resource [alfresco/core-services-context.xml]: Cannot resolve reference to bean 'customPropertyEditorRegistrar' while setting bean property 'propertyEditorRegistrars' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customPropertyEditorRegistrar' defined in class path resource [alfresco/core-services-context.xml]: Cannot resolve reference to bean 'NamespaceService' while setting bean property 'namespaceService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dictionaryDAO' defined in class path resource [alfresco/core-services-context.xml]: Cannot resolve reference to bean 'tenantService' while setting bean property 'tenantService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tenantService' defined in URL [jar:file:/usr/local/tomcat/webapps/alfresco/WEB-INF/lib/alfresco-repository-18.15.jar!/alfresco/mt/mt-context.xml]: Cannot resolve reference to bean 'tenantAdminDAO' while setting bean property 'tenantAdminDAO'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tenantAdminDAO' defined in class path resource [alfresco/dao/dao-context.xml]: Cannot resolve reference to bean 'repoSqlSessionTemplate' while setting bean property 'sqlSessionTemplate'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'repoSqlSessionTemplate' defined in class path resource [alfresco/ibatis/ibatis-context.xml]: Cannot resolve reference to bean 'repoSqlSessionFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'repoSqlSessionFactory' defined in class path resource [alfresco/ibatis/ibatis-context.xml]: Cannot resolve reference to bean 'dialectResourceLoader' while setting bean property 'resourceLoader'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dialectResourceLoader' defined in class path resource [alfresco/ibatis/ibatis-context.xml]: Cannot create inner bean 'org.springframework.beans.factory.config.PropertyPathFactoryBean#568549af' of type [org.springframework.beans.factory.config.PropertyPathFactoryBean] while setting bean property 'dialectClass'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.beans.factory.config.PropertyPathFactoryBean#568549af' defined in class path resource [alfresco/ibatis/ibatis-context.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dialect': FactoryBean threw exception on object creation; nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (The connection attempt failed.)
```

With 7.3.0 I didn't have any issue. Probably Tomcat configuration issue, which changed in 7.3.1?

**Comment by aborroy** [comment]
It looks like api-explorer hasn't been released for 7.3.1:
https://nexus.alfresco.com/nexus/#nexus-search;quick~api-explorer

I'll try to add a workaround to fix that.

**Comment by aborroy** [comment]
I've applied this approach to solve the issue:
https://github.com/aborroy/alfresco-dockerx-builder/commit/b0cfb33cb95be2b69f2890141a447280d4f19bbd

You'll need quay.io credentials.

Let me know if this works for you.

**Comment by MariusGrunenberg** [comment]
Ok it seems to be working when I simply run this image as standalone (still getting some errors, but they are db related). 

However when using it in our docker-compose/Dockerfile project, I am now getting the errors, that the alfresco group and so on are now missing. For example this here is now missing: https://github.com/aborroy/alfresco-dockerx-builder/blob/91ef576ffad7ef6cd2291bc71c81f550a7afefe8/repo/Dockerfile#L7

But probably the rest is also needed. :/

**Comment by aborroy** [comment]
Second iteration available, let me know if that helps!

**Comment by MariusGrunenberg** [comment]
Still having the issue

```
 > [quay.io/alfresco/alfresco-content-repository:7.3.1 9/9] RUN chown -R root:Alfresco /usr/local/tomcat/webapps/alfresco /usr/local/tomcat/amps /usr/local/tomcat/lib /usr/local/tomcat/shared/classes &&     chmod -R u=rwX,g=rX,o= /usr/local/tomcat/webapps/alfresco &&     chmod -R u=rwX,g=rX,o= /usr/local/tomcat/shared &&     chmod -R u=rwX,g=rX,o= /usr/local/tomcat/lib &&     chmod 664 /usr/local/tomcat/amps/*:
#0 0.240 /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
#0 0.242 chown: invalid group: 'root:Alfresco'
```

**Comment by aborroy** [comment]
I hope that is working as expected now. Thanks for your verification!

**Comment by MariusGrunenberg** [comment]
Ok perfect, it is starting now :). Thank you! Will do some testing, but looks good.

**Comment by michaeljmuller** [comment]
Is there an AGS image that includes this fix?

**Comment by MariusGrunenberg** [comment]
> I hope that is working as expected now. Thanks for your verification!

I am just seeing now, I still have some other issues now, but I noticed, that it is now not Arch64 anymore, it is AMD64 again. Probably because of the different image being pulled now. So basically, yes it starts, but it's not M1/M2 compatible anymore.

**Comment by aborroy** [comment]
That's weird. It looks like an Arch64 Docker Image for me.

Can you try giving it a different name using a different REPOSITORY name? (like "marius" and then use something like quay.io/marius/alfresco-content-repository:7.3.1)

**Comment by MariusGrunenberg** [comment]
> That's weird. It looks like an Arch64 Docker Image for me.
> 
> Can you try giving it a different name using a different REPOSITORY name? (like "marius" and then use something like quay.io/marius/alfresco-content-repository:7.3.1)

Ah yes you're right, it was because of the name. I tagged it and now it's not showing AMD64 message anymore.
